import { writeFileSync } from 'node:fs';
import { NATS_CONF, JETSTREAM_DIR } from './paths';

interface NatsConfigOptions {
  dataDir: string;
  port?: number;
}

export function generateNatsConfig(opts: NatsConfigOptions): string {
  const port = opts.port ?? 4222;
  return `# Auto-generated by @omnixal/openclaw-nats-plugin
# Do not edit manually — regenerated on setup

listen: "127.0.0.1:${port}"

jetstream {
  store_dir: "${opts.dataDir}"
  max_memory_store: 256MB
  max_file_store: 2GB
}

# Monitoring
http: "127.0.0.1:8222"
`;
}

export function writeNatsConfig(port?: number): void {
  const config = generateNatsConfig({ dataDir: JETSTREAM_DIR, port });
  writeFileSync(NATS_CONF, config);
  console.log(`NATS config written to ${NATS_CONF}`);
}
